# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cocomo-2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 431)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 129, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        spacerItem6 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_18.addWidget(self.label_20)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_19.addWidget(self.label_21)
        self.comboBox_12 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        spacerItem7 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem9)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_15.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_15.addWidget(self.pushButton_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        spacerItem10 = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_23.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_23.addWidget(self.label_25)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_22.addWidget(self.label_23)
        self.comboBox_14 = QtWidgets.QComboBox(self.tab)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.horizontalLayout_22.addWidget(self.comboBox_14)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_27.addWidget(self.label_29)
        self.comboBox_17 = QtWidgets.QComboBox(self.tab)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.horizontalLayout_27.addWidget(self.comboBox_17)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_21.addWidget(self.label_22)
        self.comboBox_13 = QtWidgets.QComboBox(self.tab)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBox_13)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_26.addWidget(self.label_28)
        self.comboBox_16 = QtWidgets.QComboBox(self.tab)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.horizontalLayout_26.addWidget(self.comboBox_16)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_28.addWidget(self.label_30)
        self.comboBox_18 = QtWidgets.QComboBox(self.tab)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.horizontalLayout_28.addWidget(self.comboBox_18)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_25.addWidget(self.label_27)
        self.comboBox_15 = QtWidgets.QComboBox(self.tab)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.horizontalLayout_25.addWidget(self.comboBox_15)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        spacerItem11 = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem12)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_24.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_24.addWidget(self.pushButton_10)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_5.addWidget(self.label_35)
        spacerItem13 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_31.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.tab_5)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_31.addWidget(self.label_34)
        self.verticalLayout_5.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_29.addWidget(self.label_31)
        self.comboBox_19 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.horizontalLayout_29.addWidget(self.comboBox_19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_39 = QtWidgets.QLabel(self.tab_5)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_36.addWidget(self.label_39)
        self.comboBox_24 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.horizontalLayout_36.addWidget(self.comboBox_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_37 = QtWidgets.QLabel(self.tab_5)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_34.addWidget(self.label_37)
        self.comboBox_22 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.horizontalLayout_34.addWidget(self.comboBox_22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_30.addWidget(self.label_32)
        self.comboBox_20 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.horizontalLayout_30.addWidget(self.comboBox_20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_32.addWidget(self.label_36)
        self.comboBox_21 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.horizontalLayout_32.addWidget(self.comboBox_21)
        self.verticalLayout_5.addLayout(self.horizontalLayout_32)
        spacerItem14 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem15)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_33.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_33.addWidget(self.pushButton_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_33)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_45 = QtWidgets.QLabel(self.tab_6)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_6.addWidget(self.label_45)
        spacerItem16 = QtWidgets.QSpacerItem(20, 91, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem16)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_43 = QtWidgets.QLabel(self.tab_6)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_40.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.tab_6)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_40.addWidget(self.label_44)
        self.verticalLayout_6.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_47 = QtWidgets.QLabel(self.tab_6)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_43.addWidget(self.label_47)
        self.comboBox_29 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.horizontalLayout_43.addWidget(self.comboBox_29)
        self.verticalLayout_6.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_46 = QtWidgets.QLabel(self.tab_6)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_41.addWidget(self.label_46)
        self.comboBox_28 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.horizontalLayout_41.addWidget(self.comboBox_28)
        self.verticalLayout_6.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_41 = QtWidgets.QLabel(self.tab_6)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_38.addWidget(self.label_41)
        self.comboBox_26 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.horizontalLayout_38.addWidget(self.comboBox_26)
        self.verticalLayout_6.addLayout(self.horizontalLayout_38)
        spacerItem17 = QtWidgets.QSpacerItem(20, 91, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem17)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem18)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_42.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_42.addWidget(self.pushButton_14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_42)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_49 = QtWidgets.QLabel(self.tab_7)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_7.addWidget(self.label_49)
        spacerItem19 = QtWidgets.QSpacerItem(20, 91, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem19)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_51 = QtWidgets.QLabel(self.tab_7)
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_47.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.tab_7)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_47.addWidget(self.label_52)
        self.verticalLayout_7.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_48 = QtWidgets.QLabel(self.tab_7)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_44.addWidget(self.label_48)
        self.comboBox_30 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.horizontalLayout_44.addWidget(self.comboBox_30)
        self.verticalLayout_7.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_50 = QtWidgets.QLabel(self.tab_7)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_45.addWidget(self.label_50)
        self.comboBox_31 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_31.setObjectName("comboBox_31")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.horizontalLayout_45.addWidget(self.comboBox_31)
        self.verticalLayout_7.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_42 = QtWidgets.QLabel(self.tab_7)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_39.addWidget(self.label_42)
        self.comboBox_27 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.horizontalLayout_39.addWidget(self.comboBox_27)
        self.verticalLayout_7.addLayout(self.horizontalLayout_39)
        spacerItem20 = QtWidgets.QSpacerItem(20, 91, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem20)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem21)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_46.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_46.addWidget(self.pushButton_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_46)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_55 = QtWidgets.QLabel(self.tab_8)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_8.addWidget(self.label_55)
        spacerItem22 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem22)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_2 = QtWidgets.QLabel(self.tab_8)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_20.addWidget(self.label_2)
        self.label_40 = QtWidgets.QLabel(self.tab_8)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_20.addWidget(self.label_40)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_56 = QtWidgets.QLabel(self.tab_8)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_49.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.tab_8)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_49.addWidget(self.label_57)
        self.verticalLayout_8.addLayout(self.horizontalLayout_49)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem23)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_58 = QtWidgets.QLabel(self.tab_8)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_50.addWidget(self.label_58)
        self.label_59 = QtWidgets.QLabel(self.tab_8)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_50.addWidget(self.label_59)
        self.verticalLayout_8.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_54 = QtWidgets.QLabel(self.tab_8)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_37.addWidget(self.label_54)
        self.label_53 = QtWidgets.QLabel(self.tab_8)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_37.addWidget(self.label_53)
        self.verticalLayout_8.addLayout(self.horizontalLayout_37)
        spacerItem24 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem24)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem25)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_48.addWidget(self.pushButton_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_48)
        self.tabWidget.addTab(self.tab_8, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Объём продукта"))
        self.label_3.setText(_translate("MainWindow", "Введите количество строк кода(в тыс.):"))
        self.pushButton_3.setText(_translate("MainWindow", "Назад"))
        self.pushButton_2.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Объём"))
        self.label_6.setText(_translate("MainWindow", "Факторы масштаба"))
        self.label_17.setText(_translate("MainWindow", "Значимость фактора"))
        self.label_5.setText(_translate("MainWindow", " Наличие опыта аналогичных разработок "))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Низкий"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Средний"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Высокий"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Критический"))
        self.label_7.setText(_translate("MainWindow", "Гибкость процесса разработки"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Низкий"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Средний"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Высокий"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Критический"))
        self.label_8.setText(_translate("MainWindow", "Архитектура и разрешение рисков "))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Низкий"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Средний"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Высокий"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Критический"))
        self.label_9.setText(_translate("MainWindow", "Сработанность команды"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Низкий"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Средний"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Высокий"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "Критический"))
        self.label_10.setText(_translate("MainWindow", "Зрелость процессов"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Низкий"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Средний"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "Высокий"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "Критический"))
        self.pushButton_4.setText(_translate("MainWindow", "Назад"))
        self.pushButton_5.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Факторы масштаба"))
        self.label_13.setText(_translate("MainWindow", "Множители трудоёмкости"))
        self.label_19.setText(_translate("MainWindow", "Приоритет"))
        self.label_12.setText(_translate("MainWindow", "квалификация персонала "))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_8.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_15.setText(_translate("MainWindow", "опыт персонала"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_10.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_10.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_11.setText(_translate("MainWindow", " разработка для повторного использования"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_14.setText(_translate("MainWindow", " сложность платформы разработки "))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_9.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_16.setText(_translate("MainWindow", " оборудование "))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_11.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_11.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_11.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_21.setText(_translate("MainWindow", "требуемое выполнение графика работ"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_12.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_12.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label.setText(_translate("MainWindow", "После этого шага готова предварительная оценка: "))
        self.pushButton.setText(_translate("MainWindow", "Перейти к оценке"))
        self.pushButton_6.setText(_translate("MainWindow", "Назад"))
        self.pushButton_7.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "МТ(пердвар.)"))
        self.label_26.setText(_translate("MainWindow", "Параметры персонала"))
        self.label_25.setText(_translate("MainWindow", "Приоритет"))
        self.label_23.setText(_translate("MainWindow", "возможности аналитика"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_14.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_14.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_14.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_14.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_14.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_29.setText(_translate("MainWindow", "опыт разработки приложений"))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_17.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_17.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_17.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_17.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_17.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_22.setText(_translate("MainWindow", "возможности программиста"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_13.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_13.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_13.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_28.setText(_translate("MainWindow", "продолжительность работы персонала"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_16.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_16.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_16.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_16.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_16.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_30.setText(_translate("MainWindow", "опыт работы с платформой"))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_18.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_18.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_18.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_18.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_18.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_27.setText(_translate("MainWindow", "опыт использования языка программирования и инструментальных средств"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_15.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_15.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_15.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_15.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_15.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.pushButton_9.setText(_translate("MainWindow", "Назад"))
        self.pushButton_10.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "МТ (Детал.)"))
        self.label_35.setText(_translate("MainWindow", "Параметры продукта"))
        self.label_34.setText(_translate("MainWindow", "Приоритет"))
        self.label_31.setText(_translate("MainWindow", "требуемая надежность программы"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_19.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_19.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_19.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_19.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_19.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_39.setText(_translate("MainWindow", "размер базы данных"))
        self.comboBox_24.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_24.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_24.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_24.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_24.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_24.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_24.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_37.setText(_translate("MainWindow", "сложность программы"))
        self.comboBox_22.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_22.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_22.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_22.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_22.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_22.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_22.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_32.setText(_translate("MainWindow", "требуемая возможность многократного использования"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_20.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_20.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_20.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_20.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_20.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_36.setText(_translate("MainWindow", "соответствие документации потребностям жизненного цикла"))
        self.comboBox_21.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_21.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_21.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_21.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_21.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_21.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_21.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.pushButton_11.setText(_translate("MainWindow", "Назад"))
        self.pushButton_12.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "МТ (Детал.)"))
        self.label_45.setText(_translate("MainWindow", "Параметры платформы"))
        self.label_44.setText(_translate("MainWindow", "Приоритет"))
        self.label_47.setText(_translate("MainWindow", "ограничения времени выполнения"))
        self.comboBox_29.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_29.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_29.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_29.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_29.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_29.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_29.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_46.setText(_translate("MainWindow", "ограничения памяти"))
        self.comboBox_28.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_28.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_28.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_28.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_28.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_28.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_28.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_41.setText(_translate("MainWindow", "изменяемость платформы"))
        self.comboBox_26.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_26.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_26.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_26.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_26.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_26.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_26.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.pushButton_13.setText(_translate("MainWindow", "Назад"))
        self.pushButton_14.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "МТ (Детал.)"))
        self.label_49.setText(_translate("MainWindow", "Параметры проекта"))
        self.label_52.setText(_translate("MainWindow", "Приоритет"))
        self.label_48.setText(_translate("MainWindow", "использование инструментальных программных средств"))
        self.comboBox_30.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_30.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_30.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_30.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_30.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_30.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_30.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_50.setText(_translate("MainWindow", "многоабонентская (удаленная) разработка"))
        self.comboBox_31.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_31.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_31.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_31.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_31.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_31.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_31.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.label_42.setText(_translate("MainWindow", "требуемое выполнение графика работ"))
        self.comboBox_27.setItemText(0, _translate("MainWindow", "Критически низкий"))
        self.comboBox_27.setItemText(1, _translate("MainWindow", "Очень низкий"))
        self.comboBox_27.setItemText(2, _translate("MainWindow", "Низкий"))
        self.comboBox_27.setItemText(3, _translate("MainWindow", "Средний"))
        self.comboBox_27.setItemText(4, _translate("MainWindow", "Высокий"))
        self.comboBox_27.setItemText(5, _translate("MainWindow", "Очень высокий"))
        self.comboBox_27.setItemText(6, _translate("MainWindow", "Критически высокий"))
        self.pushButton_15.setText(_translate("MainWindow", "Назад"))
        self.pushButton_16.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "МТ (Детал.)"))
        self.label_55.setText(_translate("MainWindow", "Итог"))
        self.label_2.setText(_translate("MainWindow", "Трудоёмкость проекта(Предвар.):"))
        self.label_40.setText(_translate("MainWindow", "333"))
        self.label_56.setText(_translate("MainWindow", "Время разработки проекта(Предвар.):"))
        self.label_57.setText(_translate("MainWindow", "111"))
        self.label_58.setText(_translate("MainWindow", "трудоёмкость проекта (Детал.):"))
        self.label_59.setText(_translate("MainWindow", "444"))
        self.label_54.setText(_translate("MainWindow", "Время разработки проекта (Детал.):"))
        self.label_53.setText(_translate("MainWindow", "222"))
        self.pushButton_8.setText(_translate("MainWindow", "Назад"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Итог"))
