# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cocomo-Intermediate.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 375)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_9.addWidget(self.comboBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_10.addWidget(self.comboBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        spacerItem6 = QtWidgets.QSpacerItem(20, 69, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_7.setObjectName("comboBox_7")
        self.horizontalLayout_17.addWidget(self.comboBox_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_15.addWidget(self.comboBox_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_16.addWidget(self.comboBox_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_8.setObjectName("comboBox_8")
        self.horizontalLayout_18.addWidget(self.comboBox_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        spacerItem7 = QtWidgets.QSpacerItem(20, 52, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_13.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_13.addWidget(self.pushButton_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        spacerItem9 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_14.addWidget(self.label_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_21.addWidget(self.label_22)
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_11.setObjectName("comboBox_11")
        self.horizontalLayout_21.addWidget(self.comboBox_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_23.addWidget(self.label_25)
        self.comboBox_12 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_12.setObjectName("comboBox_12")
        self.horizontalLayout_23.addWidget(self.comboBox_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_20.addWidget(self.label_21)
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_10.setObjectName("comboBox_10")
        self.horizontalLayout_20.addWidget(self.comboBox_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout_19.addWidget(self.comboBox_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_24.addWidget(self.label_26)
        self.comboBox_13 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_13.setObjectName("comboBox_13")
        self.horizontalLayout_24.addWidget(self.comboBox_13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        spacerItem10 = QtWidgets.QSpacerItem(20, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem11)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_22.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_22.addWidget(self.pushButton_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_31 = QtWidgets.QLabel(self.tab_6)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        spacerItem12 = QtWidgets.QSpacerItem(20, 73, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem12)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_26.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_26.addWidget(self.label_28)
        self.verticalLayout_6.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_28.addWidget(self.label_30)
        self.comboBox_15 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_15.setObjectName("comboBox_15")
        self.horizontalLayout_28.addWidget(self.comboBox_15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_27.addWidget(self.label_29)
        self.comboBox_14 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_14.setObjectName("comboBox_14")
        self.horizontalLayout_27.addWidget(self.comboBox_14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_29.addWidget(self.label_32)
        self.comboBox_16 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_16.setObjectName("comboBox_16")
        self.horizontalLayout_29.addWidget(self.comboBox_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_29)
        spacerItem13 = QtWidgets.QSpacerItem(20, 73, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem14)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_25.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_25.addWidget(self.pushButton_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_7.addWidget(self.label_36)
        spacerItem15 = QtWidgets.QSpacerItem(20, 112, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem15)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_37 = QtWidgets.QLabel(self.tab_7)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_32.addWidget(self.label_37)
        self.spinBox = QtWidgets.QSpinBox(self.tab_7)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_32.addWidget(self.spinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        spacerItem16 = QtWidgets.QSpacerItem(20, 111, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem16)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem17)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_34.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_34.addWidget(self.pushButton_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem18 = QtWidgets.QSpacerItem(20, 114, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem18)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem19 = QtWidgets.QSpacerItem(20, 114, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem19)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Выберите уровень сложности проекта"))
        self.comboBox.setItemText(0, _translate("MainWindow", "распространенный тип (organic projects)"))
        self.comboBox.setItemText(1, _translate("MainWindow", " встроенный тип (embedded projects)"))
        self.comboBox.setItemText(2, _translate("MainWindow", "полунезависимый тип (semidetached projects)"))
        self.pushButton.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Уровень"))
        self.label_12.setText(_translate("MainWindow", "Характеристики продукта"))
        self.label_7.setText(_translate("MainWindow", "Рейтинг"))
        self.label_2.setText(_translate("MainWindow", "Требуемая надежность ПО"))
        self.label_9.setText(_translate("MainWindow", "Размер БД приложения"))
        self.label_10.setText(_translate("MainWindow", "Сложность продукта"))
        self.pushButton_3.setText(_translate("MainWindow", "Назад"))
        self.pushButton_2.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Хар. прод."))
        self.label_14.setText(_translate("MainWindow", "Характеристики аппаратного обеспечения "))
        self.label_13.setText(_translate("MainWindow", "Рейтинг"))
        self.label_17.setText(_translate("MainWindow", " Ограничения быстродействия "))
        self.label_15.setText(_translate("MainWindow", "Ограничения памяти "))
        self.label_16.setText(_translate("MainWindow", "Неустойчивость окружения ВМ"))
        self.label_18.setText(_translate("MainWindow", " Требуемое время восстановления "))
        self.pushButton_5.setText(_translate("MainWindow", "Назад"))
        self.pushButton_6.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Хар. а/о"))
        self.label_20.setText(_translate("MainWindow", "Характеристики персонала"))
        self.label_24.setText(_translate("MainWindow", "Рейтинг"))
        self.label_22.setText(_translate("MainWindow", "Аналитические способности "))
        self.label_25.setText(_translate("MainWindow", "Опыт разработки "))
        self.label_21.setText(_translate("MainWindow", "Способности к разработке ПО "))
        self.label_19.setText(_translate("MainWindow", " Опыт использования виртуальных машин"))
        self.label_26.setText(_translate("MainWindow", "Опыт разработки на языках программирования"))
        self.pushButton_7.setText(_translate("MainWindow", "Назад"))
        self.pushButton_8.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Персонал"))
        self.label_31.setText(_translate("MainWindow", "Характеристики проекта"))
        self.label_28.setText(_translate("MainWindow", "Рейтинг"))
        self.label_30.setText(_translate("MainWindow", " Применение методов разработки ПО"))
        self.label_29.setText(_translate("MainWindow", "Использование инструментария разработки ПО"))
        self.label_32.setText(_translate("MainWindow", " Требования соблюдения графика"))
        self.pushButton_9.setText(_translate("MainWindow", "Назад"))
        self.pushButton_10.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Проект"))
        self.label_36.setText(_translate("MainWindow", "Еще важное уточнение"))
        self.label_37.setText(_translate("MainWindow", "Объем продукта(в тыс. строк кода):"))
        self.pushButton_11.setText(_translate("MainWindow", "Назад"))
        self.pushButton_12.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "бла"))
        self.label_3.setText(_translate("MainWindow", "Трудоёмкость(чел х месяц):"))
        self.label_4.setText(_translate("MainWindow", "1200"))
        self.label_5.setText(_translate("MainWindow", "Время разработки в календарных месяцах:"))
        self.label_6.setText(_translate("MainWindow", "2"))
        self.pushButton_4.setText(_translate("MainWindow", "Назад"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Итог"))
